sudo: required

language: sh

before_install:
    - sudo apt-get update -q
    - export scversion="stable" # or "v0.4.7", or "latest"
    - wget "https://storage.googleapis.com/shellcheck/shellcheck-${scversion}.linux.x86_64.tar.xz"
    - tar --xz -xvf shellcheck-"${scversion}".linux.x86_64.tar.xz
    - sudo cp shellcheck-"${scversion}"/shellcheck /usr/bin/
    - /usr/bin/shellcheck --version

    - sudo apt-get install imagemagick
    - sudo apt-get install gsfonts
    - sudo apt-get install p7zip-full
    - wget "https://sec.cuc.edu.cn/huangwei/course/LinuxSysAdmin/exp/chap0x04/web_log.tsv.7z"
    - 7z x web_log.tsv.7z

script:
  - bash test.sh
  - cp web_log.tsv chap0x04/web_log.tsv
  - cd chap0x04/

  # 任务一
  - bash Task_1.sh --help
  # 对文件目录下所有文件进行批处理操作，对不符合大小和分辨率要求的图片进行图片质量压缩
  - identify Timg/1.jpg
  - bash Task_1.sh -f Timg/ -j 1M 1280 1280 85
  - identify Timg/1.jpg
  # 对图片进行压缩分辨率操作
  - identify Timg/1.jpg
  - bash Task_1.sh -f Timg/1.jpg -cr 1080x1080
  - identify Timg/1.jpg
  # 支持对图片添加水印
  - bash Task_1.sh -f Timg/ -w hello
  # 支持批量重命名
  - ls Timg/
  - bash Task_1.sh -f Timg/ -a -p pre jpg
  - ls Timg/
  - bash Task_1.sh -f Timg/ -a -s suf jpg
  - ls Timg/
  # 转换图片
  - convert Timg/pre3suf.jpg Timg/pre3suf.svg
  - rm Timg/pre3suf.jpg
  - ls Timg/
  - bash Task_1.sh -f Timg/ -t
  - ls Timg/
  # 组合使用举例
  # 添加前缀，并将文件夹下svg文件转为jpg
  - rm Timg/pre3suf.jpg
  - ls Timg/
  - bash Task_1.sh -f Timg/ -a -p test jpg -t
  - ls Timg/
  # 改变分辨率，并添加后缀
  - identify Timg/pre3suf.jpg
  - bash Task_1.sh -f Timg/pre3suf.jpg -cr 1080x1080 -a -s end jpg
  - identify Timg/pre3sufend.jpg

  # 任务二
  - bash Task_2.sh worldcupplayerinfo.tsv  -h
  # 统计年龄、年龄最大、年龄最小球员
  - bash Task_2.sh worldcupplayerinfo.tsv  -a
  # 统计位置信息
  - bash Task_2.sh worldcupplayerinfo.tsv  -p
  # 统计名字最长、最短球员
  - bash Task_2.sh worldcupplayerinfo.tsv  -n

  # 任务三
  - bash Task_3.sh web_log.tsv -h
  # 统计访问来源主机TOP 100和分别对应出现的总次数，不包括IP和代理
  - bash Task_3.sh web_log.tsv -th
  # 统计访问来源主机TOP 100 IP和分别对应出现的总次数
  - bash Task_3.sh web_log.tsv -ti
  # 统计最频繁被访问的URL TOP 100
  - bash Task_3.sh web_log.tsv -tu
  # 统计不同响应状态码的出现次数和对应百分比
  - bash Task_3.sh web_log.tsv -cs
  # 分别统计不同4XX状态码对应的TOP 10 URL和对应出现的总次数
  - bash Task_3.sh web_log.tsv -c4s
  # 给定URL输出TOP 100访问来源主机
  - bash Task_3.sh web_log.tsv -osh /images/USA-logosmall.gif


after_script:
  - /usr/bin/shellcheck test.sh

after_failure:
  - id
  - pwd
  - df -h
  - cat error.log

notifications:
  email:
    on_success: never
